USE ROLE ACCOUNTADMIN;
USE DATABASE TRADING_ANALYTICS;

CREATE SCHEMA IF NOT EXISTS BRONZE;
CREATE SCHEMA IF NOT EXISTS SILVER;
CREATE SCHEMA IF NOT EXISTS GOLD;

CREATE TABLE IF NOT EXISTS BRONZE.TRADES_RAW (
  RECORD_METADATA VARIANT,
  RECORD_CONTENT VARIANT
);
