trading_pipeline:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: cr56839
      user: CAIOHANDRADELIMA
      password: Otr@conta1Health
      role: ACCOUNTADMIN
      warehouse: TRADING_WH
      database: TRADING_ANALYTICS
      schema: BRONZE
      threads: 4
