version: 2

sources:
  - name: gold
    database: TRADING_ANALYTICS
    schema: GOLD
    tables:
      - name: trading_daily_rain
      - name: trading_monthly_precipitation
      - name: trading_rainy_days_monthly
