#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=./common.sh
source "$SCRIPT_DIR/common.sh"

echo "Create .env"
echo "Run this in Snowflake with ACCOUNTADMIN to validate credentials:"
echo "SELECT CURRENT_ACCOUNT(), CURRENT_USER(), CURRENT_REGION(), CURRENT_ROLE();"
echo ""

ask() {
  local prompt="$1"
  local secret="${2:-false}"
  local value=""

  if [ "$secret" = "true" ]; then
    read -r -s -p "$prompt: " value
  else
    read -r -p "$prompt: " value
  fi

  if [ -z "$value" ]; then
    echo "Value cannot be empty."
    exit 1
  fi

  printf "%s" "$value"
}

SNOWFLAKE_ACCOUNT="$(ask "Snowflake account (example: YS80657)")"
SNOWFLAKE_USER="$(ask "Snowflake user")"
SNOWFLAKE_ORGANIZATION_NAME="$(ask "Snowflake organization name")"
SNOWFLAKE_PASSWORD="$(ask "Snowflake password" true)"

if [ -f "$ENV_FILE" ]; then
  cp "$ENV_FILE" "$ENV_FILE.bak.$(date +%s)"
  echo "Existing .env backed up."
fi

cat >"$ENV_FILE" <<EOF
# Auto-generated by scripts/setup/create_env.sh
SNOWFLAKE_ACCOUNT=$SNOWFLAKE_ACCOUNT
SNOWFLAKE_ORGANIZATION_NAME=$SNOWFLAKE_ORGANIZATION_NAME
SNOWFLAKE_USER=$SNOWFLAKE_USER
SNOWFLAKE_PASSWORD=$SNOWFLAKE_PASSWORD
SNOWFLAKE_WAREHOUSE=$SNOWFLAKE_WAREHOUSE
SNOWFLAKE_DATABASE=$SNOWFLAKE_DATABASE
SNOWFLAKE_ROLE=$SNOWFLAKE_ROLE
SNOWFLAKE_SCHEMA=$SNOWFLAKE_SCHEMA
SNOWFLAKE_TRADES_RAW_TABLE=$SNOWFLAKE_TRADES_RAW_TABLE
SNOWFLAKE_PRIVATE_KEY=$SNOWFLAKE_PRIVATE_KEY
SNOWFLAKE_PRIVATE_KEY_PASSPHRASE=$SNOWFLAKE_PRIVATE_KEY_PASSPHRASE

POSTGRES_USER=airflow
POSTGRES_PASSWORD=airflow
POSTGRES_DB=airflow

AIRBYTE_API_URL=http://host.docker.internal:8000/api/v1
AIRFLOW_FERNET_KEY=not_key
PROJECT_ROOT=$PROJECT_ROOT

TRADING_PG_HOST=local-postgres
TRADING_PG_PORT=5432
TRADING_PG_DB=trading_prod
TRADING_PG_USER=trading_user
TRADING_PG_PASSWORD=trading_password
EOF

echo ".env created at $ENV_FILE"
