USE ROLE ACCOUNTADMIN;

-- Role
CREATE ROLE IF NOT EXISTS TERRAFORM_ROLE;

-- User
CREATE USER IF NOT EXISTS TERRAFORM_USER
  PASSWORD = 'STRONG_P@SSW0RD123'
  DEFAULT_ROLE = TERRAFORM_ROLE
  MUST_CHANGE_PASSWORD = FALSE;

GRANT ROLE TERRAFORM_ROLE TO USER TERRAFORM_USER;

-- Inherit SYSADMIN powers
GRANT ROLE SYSADMIN TO ROLE TERRAFORM_ROLE;

GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE TERRAFORM_ROLE;
GRANT CREATE DATABASE  ON ACCOUNT TO ROLE TERRAFORM_ROLE;

-- Warehouse bootstrap
USE ROLE SYSADMIN;
CREATE WAREHOUSE IF NOT EXISTS TRADING_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

USE ROLE ACCOUNTADMIN;
GRANT USAGE, OPERATE ON WAREHOUSE TRADING_WH TO ROLE TERRAFORM_ROLE;
